from main import function_normalization, create_chunks, extract_metadata, build_prompt

test_prompts = [
    "make me a food delivery app",
    "create a modern login screen",
    "build flutter ecommerce app",
    "generate image prompt",
    "bnao ai prompt enhancer",
    "banao flutter ui",
    "bana do portfolio website",
    "mujhe app banado",
    "fix my python code",
    "error aa raha hai",
    "bug fix karo",
    "mera code sahi karo",
    "ye issue solve karo",
    "code khrab hai",
    "theek karo isko",
    "sae se do ai",
    "explain machine learning",
    "what is api",
    "why token used hota hai",
    "btao api kia hoti hai",
    "batao authentication kya hai",
    "ye samjhao ai",
    "write email to teacher",
    "letter likho",
    "message likho client ko",
    "email banao sir ke liye",
    "make me a professional email",
    "Hello",
    "hi",
    "test",
    "???",
    "!!!",
    "make     app",
    "MAKE ME APP",
    "Make, me!!! app???",
    "create-login-screen",
    "build_api_now",
    "fix: error in code",
    "mujhe flutter app bnao",
    "muje website banao",
    "kia tum code fix kr skte ho",
    "kese api banti hai",
    "krna kia hai ai",
    "kro isko professional",
    "btao ye bug kyu ara hai",
    "مجھے ایپ بنا دو",
    "یہ کوڈ ٹھیک کرو",
    "مجھے سمجھاؤ API کیا ہے",
    "ای میل لکھو",
    "کیا مسئلہ ہے",
    "Make me a Flutter app in Urdu",
    "mujhe English email likho",
    "create اردو poetry app",
    "fix میرا code",
    "explain یہ error",
    "write professional message in roman urdu",
    "make a food app with login and payment",
    "create dashboard admin panel",
    "build chatbot api",
    "generate prompt for logo",
    "banao ai resume analyzer",
    "bana do landing page",
    "make 10 product ideas",
    "create python script",
    "build fastapi backend",
    "fix indentation error",
    "fix syntax error",
    "bug in flutter navigation",
    "issue with git push",
    "error in terminal",
    "code not running",
    "app crash ho rahi hai",
    "emulator ni chal raha",
    "firebase issue solve karo",
    "explain neural network",
    "explain transformer",
    "what is metadata",
    "why normalization needed",
    "btao chunks kya hain",
    "samjhao tokenization",
    "kia ye architecture sahi hai",
    "kaise production ready karu",
    "write Fiverr reply",
    "write university attendance email",
    "likho client ko refund message",
    "message banao teacher ke liye",
    "email for out of city problem",
    "letter for leave application",
    "make this prompt better",
    "enhance this: make app",
    "improve my prompt",
    "professional prompt banao",
    "prompt enhancer test",
    "ai prompt ko clear karo",
    "create app, fix bug, explain api",
    "write email and create app idea",
    "btao aur code fix karo",
    "make app but explain steps",
    "??? mujhe app bnao !!!",
    "hello ai mujhe ek modern flutter food delivery app banao with login payment admin panel",
]


for user_input in test_prompts:
    normalization = function_normalization(user_input)
    chunks = create_chunks(normalization)
    metadata = extract_metadata(user_input, chunks)
    model_prompt = build_prompt(user_input, metadata)

    print("\n==============================")
    print("User Input:", user_input)
    print("Normalization:", normalization)
    print("Chunks:", chunks)
    print("Metadata:", metadata)
    print("Model Prompt:", model_prompt)


print("\nAll tests completed")
